version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: robot-postgress
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: robot

